/* 0.5.7 2021-12-27 16:37:09 */
var app=new function()
{
    this.name="​Righteous",
    this.version="1",
    this.date="2024",
    this.folder="asset-v1/",
    this.looptime=11712,
    this.bpm=82,
    this.totalframe=1024,
    this.nbpolo=7,
    this.nbloopbonus=4,
    this.bonusloopA=!0,
    this.bonusendloopA=!0,
    this.recmaxloop=23,
    this.recminloop=3,
    this.recmintime=Math.round(this.looptime/1e3)*this.recminloop,
    this.spritepolo="polo-sprite.png",
    this.spritepolotshirt="polo-sprite-tshirt.png",
    this.spritepicto="game-picto.png",
    this.colBck="#200819",
    this.col0="#FF6420",
    this.col1="#0E0D33",
    this.col2="#4553C7",
    this.col3="#FF995F",
    this.col4="#602C44",
    this.animearray=
    [
        {
            name:"b1_hiter",
            color:"74072A",
            uniqsnd:!0
        },
        {
            name:"b2_Thomas",
            color:"74072A",
            uniqsnd:!0
        },
        {
            name:"b3_Clap",
            color:"74072A",
            uniqsnd:!0
        },
        {
            name:"e1_awe",
            color:"6170E7",
            uniqsnd:!0
        },
        {
            name:"e2_meditation",
            color:"6170E7",
            uniqsnd:!0
        },
        {
            name:"m1_Ethereal",
            color:"041B57",
            uniqsnd:!0
        },
        {
            name:"m2_constellation",
            color:"041B57",
            uniqsnd:!0
        },
        {
            name:"m3_nothingness",
            color:"041B57",
            uniqsnd:!0
        },
        {
            name:"v1_PepeTheFrog",
            color:"207549",
            uniqsnd:!0
        }
    ],
    this.bonusarray=
    [
        
    ]
};